import mongoose from "mongoose";

const carSchema = new mongoose.Schema(
  {
    brand: { type: String },
    model: { type: String },
    production_years: { type: String },
    from_year: { type: String },
    to_year: { type: String },
    body_style: { type: String },
    segment: { type: String },
    title: { type: String },
    description: { type: String },
    engine_specs_title: { type: String },
    cylinders: { type: String },
    displacement: { type: String },
    power: { type: String },
    torque: { type: String },
    fuel_system: { type: String },
    fuel: { type: String },
    fuel_capacity: { type: String },
    top_speed: { type: String },
    drive_type: { type: String },
    gearbox: { type: String },
    front: { type: String },
    rear: { type: String },
    tire_size: { type: String },
    length: { type: String },
    width: { type: String },
    height: { type: String },
    front_rear_track: { type: String },
    wheelbase: { type: String },
    cargo_volume: { type: String },
    unladen_weight: { type: String },
    highway: { type: String },
    combined: { type: String },
    acceleration: { type: String },
    aerodynamics: { type: String },
    city: { type: String },
    ground_clearance: { type: String },
    gross_weight_limit: { type: String },
    brand_url: { type: String },
    brand_logo_url: { type: String },
    model_url: { type: String },		
    image_urls: { type: String },
    image_file_names: { type: [{ type: String }] },
    dir_path: { type: String },
    total_images: { type: String },			
  },
  { timestamps: true }
);

export default mongoose.model("Car", carSchema);
